
### positions 
GET http://localhost:5300/api/v1/exness/positions?symbol=BTCUSD

### positions 
GET http://localhost:5100/api/v1/exness/positions?ticket=47247020


### delete position
DELETE http://localhost:5300/api/v1/exness/positions
Content-Type: application/json

{
    "ticket": 49839876
}


### modify position by volume
PUT http://localhost:5300/api/v1/exness/positions
Content-Type: application/json

{
    "ticket": 49808521,
    "volume": 0.04
}


